language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/haynieresearch/telemetry/master/includes/travis.sh)

script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
